export const DEBUG_CONFIG = {
  enabled: import.meta.env.DEV,
  maxRequests: 100,

  models: [
    {
      id: 'anthropic/claude-sonnet-4.5',
      name: 'Claude Sonnet 4.5 ($3/$15)',
      provider: 'anthropic',
      tier: 'smart',
      isDefault: false,
    },
    {
      id: 'google/gemini-3-pro-preview',
      name: 'Gemini 3 Pro ($2/$12)',
      provider: 'google',
      tier: 'smart',
      isDefault: false,
    },
    {
      id: 'anthropic/claude-haiku-4.5',
      name: 'Claude Haiku 4.5 ($1/$5)',
      provider: 'anthropic',
      tier: 'balanced',
      isDefault: false,
    },
    {
      id: 'openai/gpt-5.1',
      name: 'GPT-5.1 ($0.30/$1.20)',
      provider: 'openai',
      tier: 'balanced',
      isDefault: false,
    },
    {
      id: 'openai/gpt-5.1-chat',
      name: 'GPT-5.1 Chat ($0.30/$1.20)',
      provider: 'openai',
      tier: 'balanced',
      isDefault: false,
    },
    {
      id: 'google/gemini-2.5-flash',
      name: 'Gemini 2.5 Flash ($0.30/$2.50)',
      provider: 'google',
      tier: 'balanced',
      isDefault: false,
    },
    {
      id: 'deepseek/deepseek-chat-v3.1',
      name: 'DeepSeek V3.1 ($0.27/$1.10)',
      provider: 'deepseek',
      tier: 'balanced',
      isDefault: false,
    },
    {
      id: 'minimax/minimax-m2',
      name: 'MiniMax M2 ($0.26/$1.02)',
      provider: 'minimax',
      tier: 'balanced',
      isDefault: false,
    },
    {
      id: 'qwen/qwen3-235b-a22b-2507',
      name: 'Qwen3 235B Instruct ($0.22/$0.95)',
      provider: 'qwen',
      tier: 'balanced',
      isDefault: false,
    },
    {
      id: 'x-ai/grok-4.1-fast',
      name: 'Grok 4.1 Fast ($0.20/$0.50)',
      provider: 'x-ai',
      tier: 'fast',
      isDefault: true,
    },
    {
      id: 'openai/gpt-4o-mini',
      name: 'GPT-4o-mini ($0.15/$0.60)',
      provider: 'openai',
      tier: 'fast',
      isDefault: false,
    },
  ],

  thresholds: {
    ttft: { good: 300, warning: 600, critical: 1000 },
    total: { good: 2000, warning: 3000, critical: 5000 },
  },

  pricing: {
    'anthropic/claude-sonnet-4.5': { input: 3.0, output: 15.0 },
    'google/gemini-3-pro-preview': { input: 2.0, output: 12.0 },
    'anthropic/claude-haiku-4.5': { input: 1.0, output: 5.0 },
    'openai/gpt-5.1': { input: 0.30, output: 1.20 },
    'openai/gpt-5.1-chat': { input: 0.30, output: 1.20 },
    'google/gemini-2.5-flash': { input: 0.30, output: 2.50 },
    'deepseek/deepseek-chat-v3.1': { input: 0.27, output: 1.10 },
    'minimax/minimax-m2': { input: 0.26, output: 1.02 },
    'qwen/qwen3-235b-a22b-2507': { input: 0.22, output: 0.95 },
    'x-ai/grok-4.1-fast': { input: 0.20, output: 0.50 },
    'openai/gpt-4o-mini': { input: 0.15, output: 0.60 },
  },
} as const
