export const DEBUG_CONFIG = {
  enabled: import.meta.env.DEV,
  maxRequests: 100,

  models: [
    {
      id: 'anthropic/claude-3.5-sonnet',
      name: 'Claude 3.5 Sonnet ($3/$15)',
      provider: 'anthropic',
      tier: 'smart',
      isDefault: false,
    },
    {
      id: 'google/gemini-2.0-flash-001',
      name: 'Gemini 2.0 Flash ($0.10/$0.40)',
      provider: 'google',
      tier: 'fast',
      isDefault: false,
    },
    {
      id: 'anthropic/claude-3.5-haiku',
      name: 'Claude 3.5 Haiku ($1/$5)',
      provider: 'anthropic',
      tier: 'balanced',
      isDefault: false,
    },
    {
      id: 'openai/gpt-4o-mini',
      name: 'GPT-4o Mini ($0.15/$0.60)',
      provider: 'openai',
      tier: 'fast',
      isDefault: false,
    },
    {
      id: 'google/gemini-flash-1.5',
      name: 'Gemini 1.5 Flash ($0.075/$0.30)',
      provider: 'google',
      tier: 'fast',
      isDefault: false,
    },
    {
      id: 'deepseek/deepseek-chat',
      name: 'DeepSeek Chat ($0.14/$0.28)',
      provider: 'deepseek',
      tier: 'balanced',
      isDefault: false,
    },
    {
      id: 'x-ai/grok-2',
      name: 'Grok 2 ($2/$10)',
      provider: 'x-ai',
      tier: 'smart',
      isDefault: false,
    },
    {
      id: 'qwen/qwen-2.5-72b-instruct',
      name: 'Qwen 2.5 72B ($0.35/$0.40)',
      provider: 'qwen',
      tier: 'balanced',
      isDefault: false,
    },
    {
      id: 'meta-llama/llama-3.1-70b-instruct',
      name: 'Llama 3.1 70B ($0.52/$0.75)',
      provider: 'meta',
      tier: 'balanced',
      isDefault: true,
    },
    {
      id: 'mistralai/mistral-small-24b-instruct-2501',
      name: 'Mistral Small ($0.10/$0.30)',
      provider: 'mistral',
      tier: 'fast',
      isDefault: false,
    },
  ],

  thresholds: {
    ttft: { good: 300, warning: 600, critical: 1000 },
    total: { good: 2000, warning: 3000, critical: 5000 },
  },

  pricing: {
    'anthropic/claude-3.5-sonnet': { input: 3.0, output: 15.0 },
    'google/gemini-2.0-flash-001': { input: 0.10, output: 0.40 },
    'anthropic/claude-3.5-haiku': { input: 1.0, output: 5.0 },
    'openai/gpt-4o-mini': { input: 0.15, output: 0.60 },
    'google/gemini-flash-1.5': { input: 0.075, output: 0.30 },
    'deepseek/deepseek-chat': { input: 0.14, output: 0.28 },
    'x-ai/grok-2': { input: 2.0, output: 10.0 },
    'qwen/qwen-2.5-72b-instruct': { input: 0.35, output: 0.40 },
    'meta-llama/llama-3.1-70b-instruct': { input: 0.52, output: 0.75 },
    'mistralai/mistral-small-24b-instruct-2501': { input: 0.10, output: 0.30 },
  },
} as const
