// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieulrkrwcgsemqeenljn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldWxya3J3Y2dzZW1xZWVubGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTc1NDYsImV4cCI6MjA3MDk5MzU0Nn0.YX6yRT9pITy76HsSpYblGDwPJ7Lyf3UKZc2kTWoQUiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});